# Generated by Django 4.1.7 on 2023-07-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'APP', 'verbose_name_plural': 'APP'},
        ),
    ]
