# Generated by Django 4.1.7 on 2023-07-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0005_alter_advertisement_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
