# Generated by Django 4.1.7 on 2023-07-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
