# Generated by Django 4.1.7 on 2023-08-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0008_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table=None,
        ),
    ]
