# Generated by Django 4.1.7 on 2023-08-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0011_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=' ', upload_to='advertisement/', verbose_name='Изображение'),
        ),
    ]
